server:
  port: 7901
  
user:
  userServicePath: http://localhost:7900/simple/

spring:
  application:
    name: microservice-simple-consumer-movie

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true

microservice-simple-provider-user:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule